export const products = [
  {
    name: 'Santol',
    tagalog: 'none',
    description: 'Round fruit with thick skin.',
    price: 60, // price in PHP per kilo
    category: 'Fruits',
    image: './Images/Santol.webp',
    quantity: 'per kilo',
  },
  {
    name: 'Soursop',
    tagalog: 'Guyabano',
    description: 'Green, spiky fruit with flesh.',
    price: 180, // price in PHP per kilo
    category: 'Fruits',
    image: './Images/Guyabano.webp',
    quantity: 'per kilo',
  },
  {
    name: 'Star Apple',
    tagalog: 'Kaimito',
    description: 'Sweet, milky flesh fruit.',
    price: 80, // price in PHP per kilo
    category: 'Fruits',
    image: './Images/Kaimito.webp',
    quantity: 'per kilo',
  },
  {
    name: 'Watermelon',
    tagalog: 'Pakwan',
    description: 'Large fruit with juicy flesh.',
    price: 50, // price in PHP per kilo
    category: 'Fruits',
    image: './Images/Pakwan.webp',
    quantity: 'per kilo',
  },
  {
    name: 'Avocado',
    tagalog: 'Abukado',
    description: 'Creamy fruit with buttery flesh.',
    price: 150, // price in PHP per kilo
    category: 'Fruits',
    image: './Images/Abukado.webp',
    quantity: 'per kilo',
  },
  {
    name: 'Apple',
    tagalog: 'Mansanas',
    description: 'Sweet, crisp fruit in colors.',
    price: 80,
    category: 'Fruits',
    image: './Images/Mansanas.webp',
    quantity: 'per kilo',
  },
  {
    name: 'Jackfruit',
    tagalog: 'Langka',
    description: 'Spiky exterior, sweet flesh.',
    price: 60,
    category: 'Fruits',
    image: './Images/Langka.webp',
    quantity: 'per kilo',
  },
  {
    name: 'Orange',
    tagalog: 'Kahel',
    description: 'Citrus fruit with juicy flesh.',
    price: 40,
    category: 'Fruits',
    image: './Images/Kahel.webp',
    quantity: 'per kilo',
  },
  {
    name: 'Strawberries',
    tagalog: 'none',
    description: 'Small, red, sweet fruit.',
    price: 150,
    category: 'Fruits',
    image: './Images/Saging_na_Tindok.webp',
    quantity: 'per kilo',
  },
  {
    name: 'Grapes',
    tagalog: 'Ubas',
    description: 'Small, sweet or tart clusters.',
    price: 120,
    category: 'Fruits',
    image: './Images/Ubas.webp',
    quantity: 'per kilo',
  },
  {
    name: 'Kiwi',
    tagalog: 'none',
    description: 'Fuzzy fruit with green flesh.',
    price: 90,
    category: 'Fruits',
    image: './Images/Kiwi.webp',
    quantity: 'per kilo',
  },
  {
    name: 'Dragonfruit',
    tagalog: 'Pitaya',
    description: 'Exotic fruit with sweet flesh.',
    price: 250,
    category: 'Fruits',
    image: './Images/Pitaya.webp',
    quantity: 'per kilo',
  },
  {
    name: 'Bitter Melon',
    tagalog: 'Ampalaya',
    description: 'Bitter fruit for Filipino dishes.',
    price: 50,
    category: 'Vegetables',
    image: './Images/Ampalaya.webp',
    quantity: 'per kilo',
  },
  {
    name: 'Bottle Gourd',
    tagalog: 'Upo',
    description: 'Young gourd for soups.',
    price: 40,
    category: 'Vegetables',
    image: './Images/Upo.webp',
    quantity: 'per kilo',
  },
  {
    name: 'Chayote',
    tagalog: 'Sayote',
    description: 'Versatile squash for dishes.',
    price: 30,
    category: 'Vegetables',
    image: './Images/Sayote.webp',
    quantity: 'per kilo',
  },
  {
    name: 'Eggplant',
    tagalog: 'Talong',
    description: 'Common vegetable in recipes.',
    price: 60,
    category: 'Vegetables',
    image: './Images/Talong.webp',
    quantity: 'per kilo',
  },
  {
    name: 'Green Amaranth',
    tagalog: 'Kalunay',
    description: 'Easy-to-cook leafy veggie.',
    price: 25,
    category: 'Vegetables',
    image: './Images/Kalunay.webp',
    quantity: 'per kilo',
  },
  {
    name: 'Hyacinth Beans',
    tagalog: 'Bataw',
    description: 'Edible beans used in cooking.',
    price: 35,
    category: 'Vegetables',
    onSale: true,
    image: './Images/Bataw.webp',
    quantity: 'per kilo',
  },
  {
    name: 'Jute Mallow',
    tagalog: 'Saluyot',
    description: 'Popular slimy vegetable.',
    price: 20,
    category: 'Vegetables',
    image: './Images/Saluyot.webp',
    quantity: 'per kilo',
  },
  {
    name: 'Lemongrass',
    tagalog: 'Tanglad',
    description: 'Fragrant herb for dishes.',
    price: 15,
    category: 'Vegetables',
    image: './Images/Tanglad.webp',
    quantity: 'per kilo',
  },
  {
    name: 'Lima Beans',
    tagalog: 'Patani',
    description: 'Climbing beans, edible parts.',
    price: 50,
    category: 'Vegetables',
    image: './Images/Patani.webp',
    quantity: 'per kilo',
  },
  {
    name: 'Long Beans',
    tagalog: 'Sitaw',
    description: 'Commonly sautéed or in soups.',
    price: 70,
    category: 'Vegetables',
    image: './Images/Sitaw.webp',
    quantity: 'per kilo',
  },
  {
    name: 'Moringa',
    tagalog: 'Malunggay',
    description: 'Leaves used in many dishes.',
    price: 20,
    category: 'Vegetables',
    image: './Images/Malunggay.webp',
    quantity: 'per kilo',
  },
  {
    name: 'Okra',
    tagalog: 'none',
    description: 'Known for slimy texture.',
    price: 40,
    category: 'Vegetables',
    image: './Images/Okra.webp',
    quantity: 'per kilo',
  },
  {
    name: 'Sponge Gourd',
    tagalog: 'Patola',
    description: 'Best consumed young.',
    price: 50,
    onSale: true,
    category: 'Vegetables',
    image: './Images/Patola.webp',
    quantity: 'per kilo',
  },
  {
    name: 'Squash',
    tagalog: 'Kalabasa',
    description: 'Used in many Filipino dishes.',
    price: 40,
    category: 'Vegetables',
    image: './Images/Kalabasa.webp',
    quantity: 'per kilo',
  },
  {
    name: 'Winged Beans',
    tagalog: 'Sigarilyas',
    description: 'All parts are edible.',
    price: 45,
    category: 'Vegetables',
    image: './Images/Sigarilyas.webp',
    quantity: 'per kilo',
  },
  {
    name: 'Sweet Potato',
    tagalog: 'Kamote',
    description: 'Used for tubers and leaves.',
    price: 30,
    category: 'Vegetables',
    image: './Images/Kamote.webp',
    quantity: 'per kilo',
  },
  {
    name: 'Mango',
    tagalog: 'Mangga',
    description: 'Sweet fruit with rich aroma.',
    price: 100,
    onSale: true,
    category: 'Fruits',
    image: './Images/Mangga.webp',
    quantity: 'per kilo',
  },
  {
    name: 'Banana',
    tagalog: 'Saging',
    description: 'Sweet fruit, fresh or cooked.',
    price: 50,
    category: 'Fruits',
    image: './Images/Saging.webp',
    quantity: 'per kilo',
  },
  {
    name: 'Papaya',
    tagalog: 'none',
    description: 'Sweet fruit in fresh dishes.',
    price: 70,
    category: 'Fruits',
    image: './Images/Papaya.webp',
    quantity: 'per kilo',
  },
  {
    name: 'Coconut',
    tagalog: 'Niyog',
    description: 'Used for juice and oil.',
    price: 40,
    category: 'Fruits',
    image: './Images/Niyog.webp',
    quantity: 'per kilo',
  },
  {
    name: 'Calamansi',
    tagalog: 'Kalamansi',
    description: 'Small citrus with sweet-sour taste.',
    price: 20,
    category: 'Fruits',
    image: './Images/Kalamansi.webp',
    quantity: 'per kilo',
  },
  {
    name: 'Guava',
    tagalog: 'Bayabas',
    description: 'Sweet, fragrant tropical fruit.',
    price: 70,
    category: 'Fruits',
    image: './Images/Bayabas.webp',
    quantity: 'per kilo',
  },
  {
    name: 'Lanzones',
    tagalog: 'none',
    description: 'Small, sweet, with a tart taste.',
    price: 120,
    category: 'Fruits',
    image: './Images/Lansones.webp',
    quantity: 'per kilo',
  },
  {
    name: 'Lychee',
    tagalog: 'Litsiyas',
    description: 'Sweet fruit with red bumpy skin.',
    price: 200,
    category: 'Fruits',
    image: './Images/Litsiyas.webp',
    quantity: 'per kilo',
  },
  {
    name: 'Mangosteen',
    tagalog: 'none',
    description: 'Tangy-sweet fruit with segments.',
    price: 250,
    category: 'Fruits',
    image: './Images/Mangosteen.webp',
    quantity: 'per kilo',
  },
  {
    name: 'Pineapple',
    tagalog: 'Pinya',
    description: 'Sweet, tangy tropical fruit.',
    price: 80,
    onSale: true,
    category: 'Fruits',
    image: './Images/Pinya.webp',
    quantity: 'per kilo',
  },
  {
    name: 'Pomelo',
    tagalog: 'Suha',
    description: 'Large citrus with sweet-tangy flesh.',
    price: 150,
    category: 'Fruits',
    image: './Images/Suha.webp',
    quantity: 'per kilo',
  },
  {
    name: 'Rambutan',
    tagalog: 'none',
    description: 'Hairy fruit with juicy sweet flesh.',
    price: 180,
    onSale: true,
    category: 'Fruits',
    image: './Images/Rambutan.webp',
    quantity: 'per kilo',
  },
  {
    name: 'Bitter Melon',
    tagalog: 'Ampalaya',
    description: 'Bitter fruit in Filipino dishes.',
    price: 50,
    category: 'Vegetables',
    image: './Images/Ampalaya.webp',
    quantity: 'per kilo',
  },
  {
    name: 'Spinach',
    tagalog: 'none',
    description: 'Leafy green vegetable rich in iron.',
    price: 30, // price in PHP per kilo
    category: 'Vegetables',
    image: './Images/Spinach.webp',
    quantity: 'per kilo',
  },
  {
    name: 'Kale',
    tagalog: 'none',
    description: 'Leafy green with a slightly bitter flavor.',
    price: 50,
    onSale: true,
    category: 'Vegetables',
    image: './Images/Kale.webp',
    quantity: 'per kilo',
  },
  {
    name: 'Bell Peppers',
    tagalog: 'none',
    description: 'Crunchy, colorful peppers used in salads.',
    price: 80,
    onSale: true,
    category: 'Vegetables',
    image: './Images/BellPeppers.webp',
    quantity: 'per kilo',
  },
  {
    name: 'Carrots',
    tagalog: 'none',
    description: 'Crunchy, sweet root vegetable.',
    price: 60,
    category: 'Vegetables',
    image: './Images/Carrots.webp',
    quantity: 'per kilo',
  },
  {
    name: 'Cucumber',
    tagalog: 'Pipino',
    description: 'Fresh, watery vegetable used in salads.',
    price: 40,
    category: 'Vegetables',
    image: './Images/Cucumber.webp',
    quantity: 'per kilo',
  },
  {
    name: 'Cauliflower',
    tagalog: 'none',
    description: 'White florets used in various dishes.',
    price: 70,
    category: 'Vegetables',
    image: './Images/Cauliflower.webp',
    quantity: 'per kilo',
  },
  {
    name: 'Pumpkin',
    tagalog: 'Kalabasa',
    description: 'Sweet orange vegetable often used in soups.',
    price: 40,
    category: 'Vegetables',
    image: './Images/Pumpkin.webp',
    quantity: 'per kilo',
  },
  {
    name: 'Zucchini',
    tagalog: 'none',
    description: 'Mild, tender green vegetable.',
    price: 60,
    category: 'Vegetables',
    image: './Images/Zucchini.webp',
    quantity: 'per kilo',
  },
];
